version: "3.8"

services:
  mongodb:
    image: mongo:5.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: 12345
#    volumes:
#      - ./db-data/:/data/db
    ports:
      - 28017:27017
